# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20171004_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='submitter',
            field=models.TextField(null=True),
        ),
    ]
